name: dart_tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# We are using `flutter` commands because
# it can be the primary usage of this package
# and because it offers more features for test coverage.
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Get Dart SDK
        uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Restore packages
        run: dart pub get

      - name: Analyze
        run: dart analyze

      - name: Run tests
        run: dart test --coverage

      - name: Upload coverage to codecov
        run: curl -s https://codecov.io/bash
        shell: bash